#!/usr/bin/env bash
# Rebuild the dyno-pony dynamic Cordis plugin.
# Use after any DSH process restart, or after editing any packages/*.js source.
#
# Since the merge (2026-09-04), all 10 historical plugins are combined into ONE
# plugin source file: packages/dyno-pony.js. It defines 34 tools in a single
# apply() and a single effect disposer.
#
# This is a documentation script — the actual host call (cordis_define +
# cordis_run) must be issued by the assistant inside the DSH session. This
# script just lists the rebuild steps in order.

set -euo pipefail
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[rebuild] dyno-pony plugin (merged)"
echo "[rebuild] skill dir: ${SKILL_DIR}"
echo ""
echo "=== Expected plugin (1 merged, was 10 separate) ==="
echo ""
echo "  Source:  packages/dyno-pony.js  (one IIFE-wrapped file, 34 tools)"
echo "  Plugin:  dp-1  / pkg-1   → dyno-pony        (34 tools)"
echo ""
echo "  Tools by section:"
echo "    pony      : ponytail                                       (1 tool)"
echo "    caveman   : caveman                                        (1 tool)"
echo "    orch      : orch_route, orch_compare, orch_pipeline, orch_status (4 tools)"
echo "    dsha      : dsh_author_inspect, _define, _run, _validate, _recover (5 tools)"
echo "    memo      : memo_classify, _format, _link, _scope, _archive, _review (6 tools)"
echo "    ptst      : ptest_template, ptest_assertions, ptest_harness (3 tools)"
echo "    cdx       : cdx_map, _symbols, _imports, _owner, _diff    (5 tools)"
echo "    mem       : mem_write, _read, _search, _promote           (4 tools)"
echo "    wf        : wf_compose, _run, _collect                    (3 tools)"
echo "    trc       : trc_mode_flow, trc_diff                       (2 tools)"
echo "  Total: 34 tools, 1 plugin, 1 effect disposer."
echo ""
echo "=== How the merge works ==="
echo ""
echo "  packages/dyno-pony.js is built by scripts/merge-plugins.cjs."
echo "  The script reads each of the 10 source files (pony.js, caveman.js, ...),"
echo "  evaluates each in a sandbox to capture its apply() body, strips the"
echo "  wrapper, and concatenates the bodies inside an IIFE per section so"
echo "  locals (note, stringOutput, session) don't collide."
echo ""
echo "  To rebuild after editing any of the 10 source files:"
echo "    node scripts/merge-plugins.cjs"
echo "  then re-define the merged file in the DSH host."
echo ""
echo "=== Rebuild for DSH host (assistant must issue these) ==="
echo ""
echo "  1. cordis_define plugin: { kind: 'new', idPrefix: 'dp' }"
echo "     name: dyno-pony-merged-v1"
echo "     purpose: One plugin with 34 tools from 10 historical plugins"
echo "     code.host: <contents of packages/dyno-pony.js>"
echo ""
echo "  2. cordis_run pluginId=<returned> packageId=<returned> mode=run"
echo ""
echo "  NOTE: the merged file is ~100KB / 2013 lines. If the assistant's"
echo "  context budget cannot carry the full file, the rebuild may need to"
echo "  happen in two passes: (a) define with the file, (b) activate."
echo ""
echo "=== After DSH restart, ask the assistant to run: ==="
echo ""
echo "  cordis_inspect_self pluginId=dp-1"
echo "  if 'no dynamic plugin dp-1': re-cordis_define as above."
echo "  else: cordis_run pluginId=dp-1 packageId=<latest> mode=run"
echo ""
echo "=== Per-task filtering (in the future) ==="
echo ""
echo "  The merged plugin registers ALL 34 tools. If we want per-task filtering"
echo "  (default overlays vs specialized), the DSH host supports it via the"
echo "  'tool filter' config (see DSH docs). For now, all 34 are always on."
echo ""
echo "=== Skill discovery (unchanged) ==="
echo ""
echo "  Skills live at /home/fares/.dsh/skills/<name>/SKILL.md       (10 skills)"
echo "  Presets live at /home/fares/.agent-presets/<id>/agent.cordis.yml  (4 presets)"
echo "  Source of truth: ${SKILL_DIR}/packages/dyno-pony.js (merged)"
echo "                    ${SKILL_DIR}/packages/<name>.js (10 originals, kept for diff)"
echo ""
echo "=== Toggle the merged plugin ==="
echo ""
echo "  cordis_stop   pluginId=dp-1     # off"
echo "  cordis_run    pluginId=dp-1 packageId=pkg-1 mode=run  # on"
echo ""
echo "=== Inspect everything that's loaded right now ==="
echo ""
echo "  cordis_inspect_list     # all providers"
echo "  cordis_inspect_query Tool listTools   # every tool the model sees (34 from dyno-pony)"
