#!/usr/bin/env bash
# rebuild.sh — rebuild and re-mount the dyno-pony dynamic Cordis plugin.
# Use after any DSH process restart, or after editing any packages/*.js source.
#
# All packages/*.js sources are merged into ONE plugin file,
# packages/dyno-pony.js — one apply(), one effect disposer. That merged file is
# the only thing the host ever sees.
#
# This is a documentation script: the real host call (cordis_define +
# cordis_run) must be issued by the assistant inside the DSH session. This
# script lists the rebuild steps in order, and every count it prints is DERIVED
# from disk by scripts/counts.cjs (E6: counters are derived, never hardcoded).
# tests/preflight.test.cjs runs this script and fails if a number here ever
# drifts from reality, so read the output as fact, not as a memory.

set -euo pipefail
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DSH="${DSH_HOME:-$HOME/.dsh}"

eval "$(node "${SKILL_DIR}/scripts/counts.cjs" --shell)"

echo "[rebuild] dyno-pony plugin (merged)"
echo "[rebuild] skill dir: ${SKILL_DIR}"
echo "[rebuild] counts: tools=${TOOLS} plugins=${PLUGINS} sources=${SOURCES} skills=${SKILLS} presets=${PRESETS}"
echo ""
echo "=== The plugin (${PLUGINS} merged file) ==="
echo ""
echo "  Source:  packages/dyno-pony.js  (one IIFE-wrapped file, ${TOOLS} tools)"
echo "  Size:    ${BUNDLE_KB} KB / ${BUNDLE_LINES} lines — do NOT paste it into context;"
echo "           mount it with the loader from README.md §Recovery (see below)."
echo ""
echo "  Tools by section (read from the bundle's own section markers):"
for s in ${SECTIONS}; do printf '    %-13s: %s tools\n' "${s%%:*}" "${s##*:}"; done
echo "  Total: ${TOOLS} tools, ${PLUGINS} plugin, 1 effect disposer."
echo ""
echo "=== How the merge works ==="
echo ""
echo "  packages/dyno-pony.js is generated by scripts/merge-plugins.cjs from the"
echo "  ${SOURCES} sources in its ORDER manifest (pony.js, caveman.js, …). Each source"
echo "  is evaluated in a sandbox to capture its apply() body, the wrapper is"
echo "  stripped, and the bodies are concatenated inside one IIFE per section so"
echo "  locals (note, stringOutput, session) cannot collide."
echo ""
echo "  Rebuild after editing any of the ${SOURCES} sources:"
echo "    node scripts/merge-plugins.cjs"
echo "  Then re-mount below. Never hand-edit packages/dyno-pony.js — the next"
echo "  merge overwrites it."
echo ""
echo "=== Mount it (the assistant must issue these) ==="
echo ""
echo "  1. cordis_define kind=new idPrefix=dyno  with the loader host code from"
echo "     README.md §Recovery. The loader reads the bundle from disk at apply"
echo "     time, so the ${TOOLS} tools never have to pass through the context."
echo "  2. cordis_run pluginId=<returned> packageId=<returned> mode=run"
echo "  3. Verify — cordis_inspect_query provider Tool method listTools must list"
echo "     all ${TOOLS} dyno-pony tools. A green run result alone is not evidence."
echo ""
echo "  If cordis_run fails with 'tool \"X\" is already registered', a stale plugin"
echo "  holds that name: cordis_inspect_self → cordis_stop pluginId=<holder> → run again."
echo ""
echo "=== After a DSH restart the plugin is gone — re-mount it ==="
echo ""
echo "  The plugin is process-local, so every id from an earlier session is dead."
echo "  Never reuse one (E5): cordis_inspect_self to find out what is loaded now,"
echo "  then go back to §Mount it — cordis_define allocates a fresh id."
echo ""
echo "=== Toggle the mounted plugin (use the ids cordis_define returned) ==="
echo ""
echo "  cordis_stop pluginId=<id>                              # off"
echo "  cordis_run  pluginId=<id> packageId=<pkg> mode=run     # on"
echo ""
echo "=== Where things live ==="
echo ""
echo "  Bundle (source of truth):  ${SKILL_DIR}/packages/dyno-pony.js"
echo "  Sources, kept for diffing: ${SKILL_DIR}/packages/<name>.js       (${SOURCES} files)"
echo "  Canonical dynamic skills:  ${SKILL_DIR}/dynamic-skills/<name>/SKILL.md  (${SKILLS})"
echo "  Runtime deployment:        ${DSH}/skills|dyno-pony   (bash scripts/install.sh)"
echo "  Presets:                   ${PRESET_DIR}   (${PRESETS} present; composition, not installed here)"
echo ""
echo "=== Per-task filtering (not used today) ==="
echo ""
echo "  The merged plugin registers ALL ${TOOLS} tools. Per-task filtering would be a"
echo "  host-side 'tool filter' config (see DSH docs); nothing here uses it yet."
