// Source-of-truth for the plugin-test specialized plugin (v1).
// Re-apply with: cordis_define plugin kind=existing pluginId=ptst-6 ...
//
// Specialized plugin for scaffolding tests for Dynamic Cordis plugins.
// Toggle on when authoring a new plugin, off when done.
// Does NOT depend on pony/caveman/orch. Self-contained; only consumes harness builtins.
//
// Three tools:
//   - ptest_template  : returns a Vitest spec body for a given tool name
//   - ptest_assertions: returns the standard 4 assertions the spec must contain
//   - ptest_harness   : returns a fake-ctx.ts builder so a plugin can mount in isolation
//
// All tools are generator-only. The model still runs `pnpm vitest` from the
// harness checkout; this plugin emits the file contents to write.

return {
  apply(ctx) {
    const POOL_KEY = 'ptest.callCount';
    const sessions = ctx.get('sessions');
    let callCount = 0;

    const note = function (text) {
      callCount += 1;
      if (callCount > 8) {
        return text + '\n\n[plugin-test] Note: ' + callCount + ' calls. Consider stopping the plugin when done authoring tests.';
      }
      return text;
    };

    const stringOutput = {
      schema: { type: 'string' },
      render: function (_args, value) { return [{ type: 'text', text: String(value) }]; },
    };

    // -------------------------------------------------------------------------
    // Tool 1: ptest_template — emit a Vitest spec body for a given tool name.
    // -------------------------------------------------------------------------
    const templateTool = harness.defineTool({
      name: 'ptest_template',
      description: 'Emit a Vitest spec body for a given dynamic plugin tool name. The spec mounts the plugin in a fake ctx, calls the tool, and asserts the standard 4 properties. The model writes the emitted string to a `.test.ts` file in the host project.',
      parameters: {
        type: 'object',
        properties: {
          toolName: { type: 'string', description: 'The model-facing tool name (e.g. "ponytail", "caveman").' },
          pluginId: { type: 'string', description: 'The cordis pluginId that owns the tool (e.g. "pony-1").' },
          packageId: { type: 'string', description: 'The cordis packageId for the current build (e.g. "pkg-9").' },
        },
        required: ['toolName', 'pluginId', 'packageId'],
      },
      output: stringOutput,
      execute: function (_args, params) {
        const t = params.toolName;
        const p = params.pluginId;
        const pkg = params.packageId;
        const out = [
          '// Generated by plugin-test. Verify against the actual tool, then add real cases.',
          '// Mounts the plugin in a fake ctx, asserts the 4 standard properties, and runs a smoke execute.',
          "import { describe, it, expect, beforeEach, afterEach } from 'vitest';",
          "import { definePlugin } from './fake-ctx';",
          "import { apply as pluginApply } from './fake-plugin-source';",
          '',
          "const TOOL_NAME = '" + t + "';",
          "const PLUGIN_ID = '" + p + "';",
          "const PACKAGE_ID = '" + pkg + "';",
          '',
          'describe(\'plugin: ' + p + ' / ' + pkg + ' / tool: ' + t + '\', () => {',
          '  let fake: ReturnType<typeof definePlugin>;',
          '  let registered: { name: string; definition: unknown } | undefined;',
          '  let disposers: Array<() => void>;',
          '',
          '  beforeEach(() => {',
          '    fake = definePlugin({ id: PLUGIN_ID, packageId: PACKAGE_ID });',
          '    disposers = [];',
          '    fake.tools.registerImpl = (def) => { registered = def; return () => { registered = undefined; }; };',
          '  });',
          '',
          '  afterEach(() => {',
          '    for (const d of disposers.splice(0)) { try { d(); } catch {} }',
          '  });',
          '',
          '  it(\'mounts without throwing\', () => {',
          '    expect(() => pluginApply(fake.ctx)).not.toThrow();',
          '  });',
          '',
          '  it(\'registers the named tool\', () => {',
          '    pluginApply(fake.ctx);',
          '    expect(registered).toBeDefined();',
          '    expect(registered!.name).toBe(TOOL_NAME);',
          '  });',
          '',
          '  it(\'exposes a valid parameter schema\', () => {',
          '    pluginApply(fake.ctx);',
          '    const def = registered!.definition as { parameters?: { type?: string; properties?: Record<string, unknown> } };',
          '    expect(def.parameters).toBeDefined();',
          '    expect(def.parameters!.type).toBe(\'object\');',
          '    expect(typeof def.parameters!.properties).toBe(\'object\');',
          '  });',
          '',
          '  it(\'exposes an output block with schema + render\', () => {',
          '    pluginApply(fake.ctx);',
          '    const def = registered!.definition as { output?: { schema?: unknown; render?: unknown } };',
          '    expect(def.output).toBeDefined();',
          '    expect(def.output!.schema).toBeDefined();',
          '    expect(typeof def.output!.render).toBe(\'function\');',
          '  });',
          '',
          '  it(\'every effect returns a disposer (no leaked registrations)\', () => {',
          '    const effectDisposers: Array<() => void> = [];',
          '    fake.ctx.effectImpl = (cb, _label) => { const d = cb(); effectDisposers.push(d); return d; };',
          '    pluginApply(fake.ctx);',
          '    expect(effectDisposers.length).toBeGreaterThan(0);',
          '    for (const d of effectDisposers) { expect(typeof d).toBe(\'function\'); d(); }',
          '  });',
          '});',
          '',
        ].join('\n');
        return note(out);
      },
    });

    // -------------------------------------------------------------------------
    // Tool 2: ptest_assertions — list the standard 4 assertions.
    // -------------------------------------------------------------------------
    const assertionsTool = harness.defineTool({
      name: 'ptest_assertions',
      description: 'Return the 4 standard assertions every dyno-pony plugin spec must contain, plus the rationale for each. Use this as a checklist when reviewing a generated spec.',
      parameters: {
        type: 'object',
        properties: {
          includeOptional: { type: 'string', description: '"yes" to also include the 3 optional assertions (effect disposer, defineTool wrap, output block). Default "yes".' },
        },
      },
      output: stringOutput,
      execute: function (_args, params) {
        const includeOptional = (params.includeOptional || 'yes') === 'yes';
        const lines = [
          '# 4 standard assertions for any dyno-pony plugin spec',
          '',
          '## Required (4)',
          '1. **mounts without throwing** — `expect(() => pluginApply(fake.ctx)).not.toThrow()`.',
          '2. **registers the named tool** — calls the apply, then asserts the tool registry received the entry with the expected `name`.',
          '3. **exposes a valid parameter schema** — `parameters.type === "object"` and `properties` is a non-empty object.',
          '4. **exposes an output block with schema + render** — `output.schema` defined, `output.render` is a function.',
          '',
        ];
        if (includeOptional) {
          lines.push('## Optional (3 — recommend including)');
          lines.push('5. **every effect returns a disposer** — call every effect\'s callback, expect each to return a `() => void`. Catches leaks.');
          lines.push('6. **uses `harness.defineTool` then `harness.registerTool`** — search the plugin source for `registerTool` and assert the argument is wrapped by `defineTool`.');
          lines.push('7. **code body ends with `};` (object literal), not `});` (call)** — a `});` at the end is the #1 dynamic plugin bug per the dsh-author skill.');
          lines.push('');
        }
        return note(lines.join('\n'));
      },
    });

    // -------------------------------------------------------------------------
    // Tool 3: ptest_harness — fake-ctx.ts builder source.
    // -------------------------------------------------------------------------
    const harnessTool = harness.defineTool({
      name: 'ptest_harness',
      description: 'Return the source for `fake-ctx.ts`, a small builder that simulates enough of the host context to mount a dyno-pony plugin in a Vitest process. Writes the file content; the model pastes it into the host project.',
      parameters: {
        type: 'object',
        properties: {},
      },
      output: stringOutput,
      execute: function (_args) {
        const out = [
          '// Generated by plugin-test. Tiny Cordis-shaped fake for dyno-pony plugin specs.',
          '//',
          '// Implements just enough of `ctx` + `harness.defineTool` + `harness.registerTool`',
          '// for a plugin body to mount in isolation under Vitest. Not a Cordis replacement.',
          '',
          'export interface FakePlugin {',
          '  ctx: FakeContext;',
          '  tools: { registerImpl: (def: unknown) => () => void };',
          '  registered: { name: string; definition: unknown }[];',
          '}',
          '',
          'export interface FakeContext {',
          '  get(name: string): unknown;',
          '  on(_name: string, _listener: (...args: unknown[]) => unknown): () => void;',
          '  effect(cb: () => () => void, _label?: string): () => void;',
          '  effectImpl: (cb: () => () => void, label?: string) => () => void;',
          '  provide(_name: string, _value: unknown): () => void;',
          '}',
          '',
          'export function definePlugin(opts: { id: string; packageId: string }): FakePlugin {',
          '  const registered: { name: string; definition: unknown }[] = [];',
          '  const services = new Map<string, unknown>();',
          '  const effects: Array<() => () => void> = [];',
          '  const defaultEffect = (cb: () => () => void, _label?: string) => {',
          '    const d = cb();',
          '    effects.push(() => d);',
          '    return d;',
          '  };',
          '  const ctx: FakeContext = {',
          '    get: (name) => services.get(name),',
          '    on: (_name, _listener) => () => {},',
          '    effect: defaultEffect,',
          '    effectImpl: defaultEffect,',
          '    provide: (name, value) => { services.set(name, value); return () => services.delete(name); },',
          '  };',
          '  return {',
          '    ctx,',
          '    registered,',
          '    tools: {',
          '      registerImpl: (def: unknown) => {',
          '        const d = def as { name: string };',
          '        registered.push({ name: d.name, definition: def });',
          '        return () => { const i = registered.findIndex((r) => r.name === d.name); if (i >= 0) registered.splice(i, 1); };',
          '      },',
          '    },',
          '  };',
          '}',
          '',
          '// Global harness shim — the plugin body expects these to exist at the',
          '// top of its function. Vitest loads fake-harness.js before the plugin.',
          '// See `vitest.config.ts` `setupFiles`.',
          'export const harness = {',
          '  defineTool: (def: unknown) => def,',
          '  registerTool: (_ctx: unknown, tool: unknown) => {',
          '    return (_ctx as FakePlugin).tools.registerImpl(tool);',
          '  },',
          '  handle: (_method: string, _handler: (...args: unknown[]) => unknown) => () => {},',
          '};',
          'globalThis.harness = harness as unknown as typeof globalThis.harness;',
          '',
        ].join('\n');
        return note(out);
      },
    });

    // -------------------------------------------------------------------------
    // Register all three.
    // -------------------------------------------------------------------------
    const d1 = harness.registerTool(ctx, templateTool);
    const d2 = harness.registerTool(ctx, assertionsTool);
    const d3 = harness.registerTool(ctx, harnessTool);

    ctx.effect(function () { return function dispose() {
      d1(); d2(); d3();
    }; }, 'ptst:dispose-all');
  },
};
