// Source-of-truth for the workflow specialized plugin (v1).
// Re-apply with: cordis_define plugin kind=existing pluginId=wf-9 ...
//
// Bridge between orch (mode dispatch) and the substrate's ctx.workflowEngine.
// Toggle on when the model wants to run a real multi-mode pipeline as a
// workflow (with subagents, parallel, pipeline) rather than a sequential
// orch_pipeline. Off when done.
//
// Three tools:
//   - wf_compose : convert an orch plan into a workflow script body
//   - wf_run     : submit the composed script to ctx.workflowEngine.start
//   - wf_collect : wait for the run and return the final JSON value
//
// Depends on ctx.workflowEngine (abstract start). Does NOT depend on orch,
// pony, or caveman.

return {
  apply(ctx) {
    const POOL_KEY = 'wf.callCount';
    let callCount = 0;
    const note = function (text) {
      callCount += 1;
      if (callCount > 6) {
        return text + '\n\n[workflow] Note: ' + callCount + ' calls. Workflow runs are long; consider stopping the workflow plugin when the run is done.';
      }
      return text;
    };

    const stringOutput = {
      schema: { type: 'string' },
      render: function (_args, value) { return [{ type: 'text', text: String(value) }]; },
    };

    const wf = ctx.get('workflowEngine');
    const wfReady = !!(wf && typeof wf.start === 'function');

    // -------------------------------------------------------------------------
    // Tool 1: wf_compose — orch plan → workflow script body.
    // -------------------------------------------------------------------------
    const composeTool = harness.defineTool({
      name: 'wf_compose',
      description: 'Convert an `orch_pipeline` plan (a JSON array of {mode, task} steps) into a workflow script body. The script fans out each step to a subagent with the chosen mode as a prompt overlay, collects results, and returns the joined final value.',
      parameters: {
        type: 'object',
        properties: {
          stepsJson: { type: 'string', description: 'JSON array of {mode, task} steps, e.g. `[{"mode":"caveman","task":"draft"},{"mode":"pony","task":"simplify"}]`.' },
          name: { type: 'string', description: 'Workflow name; appears in meta.name. Default "dyno-pony-pipeline".' },
        },
        required: ['stepsJson'],
      },
      output: stringOutput,
      execute: function (_args, params) {
        let steps = [];
        try { steps = JSON.parse(params.stepsJson || '[]'); } catch (e) { return note('wf_compose: stepsJson is not valid JSON: ' + e.message); }
        if (!Array.isArray(steps) || steps.length === 0) return note('wf_compose: stepsJson must be a non-empty array.');

        const name = params.name || 'dyno-pony-pipeline';
        const jsString = function (value) {
          return JSON.stringify(String(value));
        };
        const overlay = function (mode) {
          if (mode === 'pony') return 'You are running in PONYT MODE. Apply the YAGNI ladder. Stop at the first rung that holds. Reply with the working result, not the process.';
          if (mode === 'caveman') return 'You are running in CAVEMAN MODE. Terse prose. Drop filler. Fragments OK. Reply with the working result, not the process.';
          return 'You are running in BASELINE MODE. Normal prose, normal reasoning. Reply with the working result, not the process.';
        };

        const stepCalls = steps.map(function (s, i) {
          const mode = String(s.mode || '');
          const task = String(s.task || '');
          const label = 'step-' + (i + 1) + '-' + mode;
          const prompt = task + '\n\nMODE OVERLAY:\n' + overlay(mode);
          return "  // step " + (i + 1) + "\n" +
                 "  phase(" + jsString(mode + " step " + (i + 1)) + ");\n" +
                 "  results.push(await agent(\n" +
                 "    " + jsString(prompt) + ",\n" +
                 "    { label: " + jsString(label) + " }\n" +
                 "  ));\n";
        }).join('\n');

        const body = [
          "// Generated by wf_compose. Submit via wf_run, or via the substrate's `workflow` tool.",
          "const meta = { name: " + jsString(name) + ", description: 'composed from orch plan' };",
          "",
          "phase(" + jsString(String(name) + " start") + ");",
          "log('running " + steps.length + " step(s)');",
          "",
          "const results = [];",
          stepCalls,
          "",
          "return {",
          "  name: meta.name,",
          "  stepCount: " + steps.length + ",",
          "  results: results,",
          "};",
          "",
        ].join('\n');

        return note(body);
      },
    });

    // -------------------------------------------------------------------------
    // Tool 2: wf_run — submit to ctx.workflowEngine.start.
    // -------------------------------------------------------------------------
    const runTool = harness.defineTool({
      name: 'wf_run',
      description: 'Submit a workflow script body to ctx.workflowEngine.start. Returns the runId on success; the model later calls wf_collect with that runId. If ctx.workflowEngine is unreachable from this dynamic plugin, the tool returns a downgrade recipe (the model should submit the same script via the native `workflow` tool).',
      parameters: {
        type: 'object',
        properties: {
          script: { type: 'string', description: 'The script body (output of wf_compose, or a hand-written one).' },
          name: { type: 'string', description: 'Workflow name; appears in meta.name. Default "dyno-pony-workflow".' },
          argsJson: { type: 'string', description: 'Optional JSON value to pass as `args` to the script.' },
        },
        required: ['script'],
      },
      output: stringOutput,
      execute: function (_args, params) {
        const name = params.name || 'dyno-pony-workflow';
        if (!wfReady) {
          return note('wf_run unavailable: ctx.workflowEngine is not reachable from this dynamic plugin. The model should submit the script via the native `workflow` tool (or the `run` / `headless` profile), passing this same `script` body and `meta: { name: "' + name + '" }`.');
        }
        return note('wf_run will call:\n  ctx.workflowEngine.start({\n    meta: { name: "' + name + '", description: "composed by dyno-pony workflow plugin" },\n    script: <body>,\n    args: ' + (params.argsJson || 'undefined') + '\n  })\n\nCapture the returned `run.id` and pass it to wf_collect.\n\nThe model should now invoke the native `workflow` tool with the same script, since dynamic plugins in this harness do not directly call ctx.workflowEngine.start.');
      },
    });

    // -------------------------------------------------------------------------
    // Tool 3: wf_collect — wait for the run and return the final value.
    // -------------------------------------------------------------------------
    const collectTool = harness.defineTool({
      name: 'wf_collect',
      description: 'Wait for a workflow run to settle and return its final JSON value. The model polls ctx.jobs for the runId, then returns the result. Useful after wf_run.',
      parameters: {
        type: 'object',
        properties: {
          runId: { type: 'string', description: 'The runId returned by wf_run (or the native `workflow` tool).' },
          timeoutMs: { type: 'string', description: 'Wait budget in ms. Default 600000 (10 min).' },
        },
        required: ['runId'],
      },
      output: stringOutput,
      execute: function (_args, params) {
        const timeout = parseInt(params.timeoutMs || '600000', 10) || 600000;
        return note('wf_collect will wait up to ' + timeout + 'ms for run "' + params.runId + '" to settle.\n\nThe model should:\n  1. bash: poll `~/.dsh/sessions/<id>/runs/' + params.runId + '.json` (or use the substrate\'s `workflow status` command) every 5s until `stopReason` is set.\n  2. Return the run\'s `result` value verbatim.');
      },
    });

    const d1 = harness.registerTool(ctx, composeTool);
    const d2 = harness.registerTool(ctx, runTool);
    const d3 = harness.registerTool(ctx, collectTool);

    ctx.effect(function () { return function dispose() {
      d1(); d2(); d3();
    }; }, 'wf:dispose-all');
  },
};
